#ifndef UV_K5_FIRMWARE_CUSTOM_0_17_CHINESE_H
#define UV_K5_FIRMWARE_CUSTOM_0_17_CHINESE_H

#define 步进频率 "Step"
#define 接收数字亚音 "RxDCS"
#define 接收模拟亚音 "RxCTCS"
#define 发送数字亚音 "TxDCS"
#define 发送模拟亚音 "TxCTCS"
#define 频差方向 "TxODir"
#define 频差频率 "TxOffs"
#define 加密 "Scramb"
#define 遇忙禁发 "BusyCL"
#define 压扩 "Compnd"
#define 存置信道 "ChSave"
#define 删除信道 "ChDele"
#define 命名信道 "ChName"
#define 信道扫描列表 "SList"
#define 扫描列表1 "SList1"
#define 扫描列表2 "SList2"
#define 搜索恢复模式 "ScnRev"
#define 发送超时 "TxTOut"
#define 省电模式 "BatSav"
#define 麦克风增益 "Mic"
#define 信道显示模式 "ChDisp"
#define 自动背光 "BackLt"
#define 背光亮度 "Light"
#define 首尾音 "Roger"
#define MDC_ID "MDC ID"
#define 尾音消除 "STE"
#define 过中继尾音消除 "RP STE"
#define 按键即呼 "1 Call"
#define DTMF_ID "D ID"
#define DTMF上线码 "UPCode"
#define DTMF下线码 "DWCode"
#define DTMF发送 "PTT ID"
#define DTMF侧音 "D ST"
#define DTMF响应 "D Resp"
#define DTMF复位 "D Hold"
#define DTMF预载波 "D Prel"
#define DTMF联系人 "D List"
#define DTMF显示 "D Live"
#define AM自动增益 "AM Fix"
#define 收发模式 "RxMode"
#define 静噪等级 "Sql"
#define 频段解锁 "F Lock"
#define 两百M发射 "Tx 200"
#define 三百五十M发射 "Tx 350"
#define 五百M发射 "Tx 500"
#define 三百五十M接收 "350 En"
#define 电池调压 "BatCal"
#define 电池大小 "BatVol"
#define 参数复位 "Reset"
#define 发送等于接收 "OFF"
#define 发送等于接收加偏移 "+"
#define 发送等于接收减偏移 "-"
#define 关闭 "OFF"
#define 开启 "ON"
#define 一级 "1:1"
#define 二级 "1:2"
#define 三级 "1:3"
#define 四级 "1:4"
#define 三十秒 "30 sec"
#define 一分 "1 min"
#define 两分 "2 min"
#define 三分 "3 min"
#define 四分 "4 min"
#define 五分 "5 min"
#define 六分 "6 min"
#define 七分 "7 min"
#define 八分 "8 min"
#define 九分 "9 min"
#define 十五分 "15 min"
#define 主信道接收发射 "MAIN\nONLY"
#define 双信道接收 "DUAL RX\nRESPOND"
#define 主信道发射副信道接收 "CROSS\nBAND"
#define 主信道发射双信道接收 "MAIN TX\nDUAL RX"
#define 遇信号5秒后搜索 "TIME"
#define 信号停止后搜索 "CARRIER"
#define 遇信号后停止搜索 "STOP"
#define 频率 "FREQ"
#define 信道号 "CHANNEL\nNUMBER"
#define 名称 "NAME"
#define 名称加频率 "NAME +\nFREQ"
#define 不响应 "DO\nNOTHING"
#define 本地响铃 "RING"
#define 回复响应 "REPLY"
#define 本地响铃回复响应 "BOTH"
#define 不发送 "OFF"
#define 上线码 "UP CODE"
#define 下线码 "DOWN CODE"
#define 上线加下线码 "UP+DOWN\nCODE"
#define Quindar码 "APOLLO\nQUINDAR"
#define 关闭 "OFF"
#define ROGER尾音 "ROGER"
#define MDC尾音 "MDC\nEND"
#define MDC首音 "MDC\nBGN"
#define MDC首尾音 "MDC\nBOTH"
#define MDC首音加ROGER "MDC BGN\n+ROGER"
#define 除信道参数 "VFO"
#define 全部参数 "ALL"
#define 禁用全部 "DISABLE\nALL"
#define 解锁全部 "UNLOCK\nALL"
#define 五秒 "5 sec"
#define 十秒 "10 sec"
#define 二十秒 "20 sec"
#define 发送时 "TX"
#define 接收时 "RX"
#define 发送接收时 "TX/RX"
#define 全部 "ALL"
#define 扫描 "Scan"
#define 低电压 "LOW VOL"
#define 遇忙 "BUSY"
#define 禁止发射 "DISABLE"
#define 发送超时 "TxTOut"
#define 高电压 "HIGH VOL"
#define 按EXIT键 "Press EXIT"
#define 存置问 "SAVE?"
#define 存置了 "SAVED!"
#define 删除问 "DEL?"
#define 列表 "List"
#define 模拟亚音 "CTCS"
#define 数字亚音 "DCS"
#define 图片 "PIC"
#define 信息 "TxT"
#define 侧键1短按 "F1Shrt"
#define 侧键1长按 "F1Long"
#define 侧键2短按 "F2Shrt"
#define 侧键2长按 "F2Long"
#define M键长按 "M Long"
#define 手电 "LIGHT"
#define 切换发射功率 "POWER"
#define 监听 "MONITOR"
#define 声控发射 "VOX"
#define FM收音机 "FM RADIO"
#define 锁定按键 "LOCK KEY"
#define 切换信道 "SWITCH VFO"
#define 切换信道模式 "VFO/MR"
#define 切换调制模式 "Demodu"
#define DTMF解码 "D Decd"
#define 切换宽窄带 "W/N"
#define 宽窄带 "W/N"
#define 宽带 "WIDE"
#define 窄带 "NARROW"
#define 主信道发射 "MAIN SEND"
#define 副信道发射 "DUAL SEND"
#define 开机显示 "POnMsg"



#endif
